
package org.example.aggregate.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Mon Mar 31 14:35:45 EST 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "add", namespace = "http://aggregate.example.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "add", namespace = "http://aggregate.example.org/", propOrder = {"arg0", "arg1"})

public class Add {

    @XmlElement(name = "arg0")
    private java.lang.Integer arg0;
    @XmlElement(name = "arg1")
    private java.lang.Integer arg1;

    public java.lang.Integer getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Integer newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.Integer getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.Integer newArg1)  {
        this.arg1 = newArg1;
    }

}

