package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-28T12:09:43.334+11:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "ComplexServiceImplService", 
                  wsdlLocation = "http://localhost:8383/service_sample_proxy/services_proxy/proxyport?wsdl",
                  targetNamespace = "http://webservice/") 
public class ComplexServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "ComplexServiceImplService");
    public final static QName ComplexServiceImplPort = new QName("http://webservice/", "ComplexServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8383/service_sample_proxy/services_proxy/proxyport?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ComplexServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/complexserviceimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ComplexServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComplexServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComplexServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComplexServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComplexServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComplexServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ComplexService
     */
    @WebEndpoint(name = "ComplexServiceImplPort")
    public ComplexService getComplexServiceImplPort() {
        return super.getPort(ComplexServiceImplPort, ComplexService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComplexService
     */
    @WebEndpoint(name = "ComplexServiceImplPort")
    public ComplexService getComplexServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ComplexServiceImplPort, ComplexService.class, features);
    }

}
