package example.wrapped.divide;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0 2014-03-30T10:05:08.195+11:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://example/wrapped/divide", name = "divide")
@XmlSeeAlso({ org.example.divide.ObjectFactory.class,
		org.example.divideresponse.ObjectFactory.class })
public class DivideImpl implements Divide {

	@WebResult(name = "sum", targetNamespace = "http://www.example.org/divideResponse")
	@RequestWrapper(localName = "divide", targetNamespace = "http://www.example.org/divide", className = "org.example.divide.Divide")
	@WebMethod(action = "http://example/wrapped/divide")
	@ResponseWrapper(localName = "divideResponse", targetNamespace = "http://www.example.org/divideResponse", className = "org.example.divideresponse.DivideResponse")
	public int divide(
			@WebParam(name = "argumentOne", targetNamespace = "http://www.example.org/divide") int argumentOne,
			@WebParam(name = "argumentTwo", targetNamespace = "http://www.example.org/divide") int argumentTwo) {
		return argumentOne / argumentTwo;
	}
}
