<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WebserviceClassService" targetNamespace="http://webservice/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://webservice/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://webservice/" schemaLocation="webserviceclass_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="invokeMe">
    <wsdl:part name="parameters" element="tns:invokeMe">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="invokeMeResponse">
    <wsdl:part name="parameters" element="tns:invokeMeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ServiceInterface">
    <wsdl:operation name="invokeMe">
      <wsdl:input name="invokeMe" message="tns:invokeMe">
    </wsdl:input>
      <wsdl:output name="invokeMeResponse" message="tns:invokeMeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WebserviceClassServiceSoapBinding" type="tns:ServiceInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="invokeMe">
      <soap:operation soapAction="urn:InvokeMe" style="document"/>
      <wsdl:input name="invokeMe">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="invokeMeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WebserviceClassService">
    <wsdl:port name="WebserviceClassPort" binding="tns:WebserviceClassServiceSoapBinding">
      <soap:address location="http://localhost:9090/WebserviceClassPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
