
package org.example.aggregate.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Mon Mar 31 14:35:45 EST 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "addResponse", namespace = "http://aggregate.example.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addResponse", namespace = "http://aggregate.example.org/")

public class AddResponse {

    @XmlElement(name = "return")
    private java.lang.Integer _return;

    public java.lang.Integer getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.Integer new_return)  {
        this._return = new_return;
    }

}

