package org.example.aggregate;

import java.util.Iterator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0 2014-03-31T13:11:09.567+11:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://www.example.org/aggregate/", name = "MathOperation", endpointInterface = "org.example.aggregate.MathOperationInterface")
@XmlSeeAlso({ org.example.multiply.ObjectFactory.class, ObjectFactory.class,
		org.example.addlistresponse.ObjectFactory.class,
		org.example.subtractresponse.ObjectFactory.class,
		org.example.divide.ObjectFactory.class,
		org.example.add.ObjectFactory.class,
		org.example.multiplyresponse.ObjectFactory.class,
		org.example.addlist.ObjectFactory.class,
		org.example.divideresponse.ObjectFactory.class,
		org.example.subtract.ObjectFactory.class,
		org.example.addresponse.ObjectFactory.class })
public class MathOperationImpl implements MathOperation, MathOperationInterface {

	@WebResult(name = "sum", targetNamespace = "")
	@RequestWrapper(localName = "addList", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.addlist.AddList")
	@WebMethod
	@ResponseWrapper(localName = "addListResponse", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.addlistresponse.AddListResponse")
	public java.lang.Integer addList(
			@WebParam(name = "arguments", targetNamespace = "http://www.example.org/addList") java.util.List<java.lang.Integer> arguments) {
		int sum = 0;

		for (Iterator iterator = arguments.iterator(); iterator.hasNext();) {
			Integer integer = (Integer) iterator.next();

			sum += integer;

		}

		return sum;
	}

	@WebResult(name = "sum", targetNamespace = "")
	@RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.add.Add")
	@WebMethod(action = "http://www.example.org/aggregate/add")
	@ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.addresponse.AddResponse")
	public java.lang.Integer add(
			@WebParam(name = "argumentOne", targetNamespace = "http://www.example.org/add") java.lang.Integer argumentOne,
			@WebParam(name = "argumentTwo", targetNamespace = "http://www.example.org/add") java.lang.Integer argumentTwo) {
		return argumentOne + argumentTwo;
	}

	@WebResult(name = "sum", targetNamespace = "")
	@RequestWrapper(localName = "subtract", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.subtract.Subtract")
	@WebMethod
	@ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.subtractresponse.SubtractResponse")
	public int subtract(
			@WebParam(name = "argumentOne", targetNamespace = "http://www.example.org/subtract") int argumentOne,
			@WebParam(name = "argumentTwo", targetNamespace = "http://www.example.org/subtract") int argumentTwo) {
		return argumentOne - argumentTwo;

	}

	@WebResult(name = "sum", targetNamespace = "")
	@RequestWrapper(localName = "multiply", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.multiply.Multiply")
	@WebMethod
	@ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.multiplyresponse.MultiplyResponse")
	public int multiply(
			@WebParam(name = "argumentOne", targetNamespace = "http://www.example.org/multiply") int argumentOne,
			@WebParam(name = "argumentTwo", targetNamespace = "http://www.example.org/multiply") int argumentTwo) {
		return argumentOne * argumentTwo;

	}

	@WebResult(name = "sum", targetNamespace = "")
	@RequestWrapper(localName = "divide", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.divide.Divide")
	@WebMethod
	@ResponseWrapper(localName = "divideResponse", targetNamespace = "http://www.example.org/aggregate/", className = "org.example.divideresponse.DivideResponse")
	public int divide(
			@WebParam(name = "argumentOne", targetNamespace = "http://www.example.org/divide") int argumentOne,
			@WebParam(name = "argumentTwo", targetNamespace = "http://www.example.org/divide") int argumentTwo) {
		return argumentOne / argumentTwo;

	}
}
