
package webservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-03-28T09:11:38.485+11:00
 * Generated source version: 2.7.8
 * 
 */
 
public class ComplexServiceServer{

    protected ComplexServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new webservice.ComplexServiceImpl();
        String address = "http://localhost:9090/ComplexServiceImplPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ComplexServiceServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 