package example.wrapped.mathoperation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-31T14:17:22.364+11:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "mathService", 
                  wsdlLocation = "file:/D:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/mathoperation.wsdl",
                  targetNamespace = "http://example/wrapped/mathoperation") 
public class MathService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example/wrapped/mathoperation", "mathService");
    public final static QName MathSoapPort = new QName("http://example/wrapped/mathoperation", "mathSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/mathoperation.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MathService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/mathoperation.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MathService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MathService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MathService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MathService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MathService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MathOperation
     */
    @WebEndpoint(name = "mathSoapPort")
    public MathOperation getMathSoapPort() {
        return super.getPort(MathSoapPort, MathOperation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathOperation
     */
    @WebEndpoint(name = "mathSoapPort")
    public MathOperation getMathSoapPort(WebServiceFeature... features) {
        return super.getPort(MathSoapPort, MathOperation.class, features);
    }

}
