package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-03-24T12:15:34.857+11:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://webservice/", name = "ServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "invokeMe", targetNamespace = "http://webservice/", className = "webservice.InvokeMe")
    @WebMethod(action = "urn:InvokeMe")
    @ResponseWrapper(localName = "invokeMeResponse", targetNamespace = "http://webservice/", className = "webservice.InvokeMeResponse")
    public java.lang.String invokeMe(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
