
package webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Sat Apr 05 15:39:25 EST 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "multiArgumentMethod", namespace = "http://webservice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multiArgumentMethod", namespace = "http://webservice/")

public class MultiArgumentMethod {

    @XmlElement(name = "arg0")
    private java.util.List<webservice.RequestBean> arg0;

    public java.util.List<webservice.RequestBean> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.List<webservice.RequestBean> newArg0)  {
        this.arg0 = newArg0;
    }

}

