
package webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Fri Mar 28 09:11:38 EST 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "sampleMethodResponse", namespace = "http://webservice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sampleMethodResponse", namespace = "http://webservice/")

public class SampleMethodResponse {

    @XmlElement(name = "return")
    private webservice.RequestDataResponse _return;

    public webservice.RequestDataResponse getReturn() {
        return this._return;
    }

    public void setReturn(webservice.RequestDataResponse new_return)  {
        this._return = new_return;
    }

}

