
package webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Sat Apr 05 18:26:08 EST 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "splitServiceResponse", namespace = "http://webservice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "splitServiceResponse", namespace = "http://webservice/")

public class SplitServiceResponse {

    @XmlElement(name = "return")
    private webservice.ResponseBean _return;

    public webservice.ResponseBean getReturn() {
        return this._return;
    }

    public void setReturn(webservice.ResponseBean new_return)  {
        this._return = new_return;
    }

}

