
package webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Sat Apr 05 19:57:03 EST 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "splitList", namespace = "http://webservice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "splitList", namespace = "http://webservice/")

public class SplitList {

    @XmlElement(name = "arg0")
    private java.util.List<webservice.RequestBean> arg0;

    public java.util.List<webservice.RequestBean> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.List<webservice.RequestBean> newArg0)  {
        this.arg0 = newArg0;
    }

}

