
package webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Sat Apr 05 19:57:03 EST 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "splitListResponse", namespace = "http://webservice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "splitListResponse", namespace = "http://webservice/")

public class SplitListResponse {

    @XmlElement(name = "return")
    private java.util.List<webservice.ResponseBean> _return;

    public java.util.List<webservice.ResponseBean> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<webservice.ResponseBean> new_return)  {
        this._return = new_return;
    }

}

