package example.wrapped.multiply;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-30T10:05:01.962+11:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "multiplyService", 
                  wsdlLocation = "file:/d:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/multiply.wsdl",
                  targetNamespace = "http://example/wrapped/multiply") 
public class MultiplyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example/wrapped/multiply", "multiplyService");
    public final static QName MultiplySoapPort = new QName("http://example/wrapped/multiply", "multiplySoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/d:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/multiply.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MultiplyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/d:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/multiply.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MultiplyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MultiplyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiplyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MultiplyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MultiplyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MultiplyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Multiply
     */
    @WebEndpoint(name = "multiplySoapPort")
    public Multiply getMultiplySoapPort() {
        return super.getPort(MultiplySoapPort, Multiply.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Multiply
     */
    @WebEndpoint(name = "multiplySoapPort")
    public Multiply getMultiplySoapPort(WebServiceFeature... features) {
        return super.getPort(MultiplySoapPort, Multiply.class, features);
    }

}
