package example.wrapped.add;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-30T10:04:46.714+11:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://example/wrapped/add", name = "add")
@XmlSeeAlso({org.example.add.ObjectFactory.class, org.example.addresponse.ObjectFactory.class})
public interface Add {

    @WebResult(name = "sum", targetNamespace = "http://www.example.org/addResponse")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/add", className = "org.example.add.Add")
    @WebMethod(action = "http://example/wrapped/add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/addResponse", className = "org.example.addresponse.AddResponse")
    public int add(
        @WebParam(name = "argumentOne", targetNamespace = "http://www.example.org/add")
        int argumentOne,
        @WebParam(name = "argumentTwo", targetNamespace = "http://www.example.org/add")
        int argumentTwo
    );
}
