
package a.b.c.d.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.8
 * Mon Mar 31 14:50:15 EST 2014
 * Generated source version: 2.7.8
 */

@XmlRootElement(name = "addList", namespace = "http://d.c.b.a/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addList", namespace = "http://d.c.b.a/")

public class AddList {

    @XmlElement(name = "arg0")
    private java.util.List<java.lang.Integer> arg0;

    public java.util.List<java.lang.Integer> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.List<java.lang.Integer> newArg0)  {
        this.arg0 = newArg0;
    }

}

