package example.wrapped.add;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2014-03-30T10:04:46.808+11:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "addService", 
                  wsdlLocation = "file:/d:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/add.wsdl",
                  targetNamespace = "http://example/wrapped/add") 
public class AddService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example/wrapped/add", "addService");
    public final static QName AddSoapPort = new QName("http://example/wrapped/add", "addSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/d:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/add.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AddService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/d:/PFG_Applications/IDE/workspace-gwtp-old/service/WebContent/wsdl/add.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AddService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AddService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AddService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AddService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AddService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Add
     */
    @WebEndpoint(name = "addSoapPort")
    public Add getAddSoapPort() {
        return super.getPort(AddSoapPort, Add.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Add
     */
    @WebEndpoint(name = "addSoapPort")
    public Add getAddSoapPort(WebServiceFeature... features) {
        return super.getPort(AddSoapPort, Add.class, features);
    }

}
